### ISSUE TITLE
Unterminated quote string

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [arboleya/electrify#10]
![screenshot from 2015-09-11 04 20 06](https://cloud.githubusercontent.com/assets/12840136/9809181/781306ac-583c-11e5-88d7-135ede78dfe4.png)
The app runs fine when running throught "meteor run", however when trying to run the dist version, I get this strange error =(

**Comment by rafaelcorreiapoli** [comment]
Electrified: 1: Electrified: ELF: not found
Electrified: 1: Electrified: Syntax error: Unterminated quoted string

**Comment by arboleya** [comment]
Well thats is new, I'll need to emulate it first.

Ubuntu right? What version?

**Comment by arboleya** [comment]
Also, can you provide a simple repo reproducing this behavior? So we can go down in a less esoteric way about fixing this. :)

**Comment by rafaelcorreiapoli** [comment]
I discovered what was happening, i ran electrify as root then it created a file on my tmp: electrify-ppid
when I closed it, the file was not deleted and then I couldn't open the app anymore
I deleted the tmp file and did everything again but with my own user... now this problem is fixed
Although, i still have the problem that the app freezes on an empty screen when running the app for the second time (it only works on the first time)

**Comment by rafaelcorreiapoli** [comment]
Ubuntu 14.04 LTS

**Comment by arboleya** [comment]
Can you provide a simple repo reproducing this behavior, so I can start on the right foot?

**Comment by rafaelcorreiapoli** [comment]
It happened just by creating a new meteor project and adding the electrify package
It was not a problem with the package itself, but with my tmp directory, in my ubuntu
I think that would be great if you manage to delete that electrify-ppid from tmp folder when the process is finished, to avoid this kind of problems

**Comment by arboleya** [comment]
Hmm ok.

Electrify itself doesn't create this ppid, perhaps it's something automatically created by Electron itself.

I'm gonna dig into it this weekend, let's see.

**Comment by arboleya** [comment]
Oh now I see, you are trying to run a binary through shell, remove the `sh` part and it will proceed.

``` shell
.electrified/.dist/Electrified-linux-x64/Electrified
```

Or, outside terminal, just double click the file's icon.
