### ISSUE TITLE
If you put your project in a folder called "app", it will not work.

### ISSUE THREAD

**Issue by AlexFrazer** [arboleya/electrify#20]
Eg:

```
app/
  .meteor/
  client/
  server/
  lib/
README.md
```

This won't work.

**Comment by arboleya** [comment]
I can imagine how this would happen, gonna check it.

Out of curiosity, are you trying [electron-builder](https://github.com/loopline-systems/electron-builder)?

**Comment by challett** [comment]
I can confirm this.  Package was not working until I renamed my folder

**Comment by arboleya** [comment]
Should be fixed in `2.0.0` - check out the new API / usage in project README.

Please re-open in case of any problem.
