### ISSUE TITLE
Meteor installation required for running .exe

### ISSUE THREAD

**Issue by ericdepotter** [arboleya/electrify#21]
### General description

Does meteor need to be installed when you want to run the generated .exe?

Because when I run the exe on another windows pc which does not have meteor installed. The following error occurs (runs fine on the pc that packaged it):

```
Error: ENOENT: no such file or directory, open 'C:\Users\...\Appdata\Local\.meteor\meteor.bat'
```

![screenshot](https://cloud.githubusercontent.com/assets/2463859/10666125/0028719a-78d0-11e5-899f-76f6b21e9320.png)

If this is the case then why is meteor bundled in the generation process?
### Generation process
1. Removed ./.electrify folder
2. Started meteor app
3. Set name in ./.electrify/package.json
4. Restarted app
5. Ran 'Electrify.app.package()' in 'meteor shell' using new command line

The resulting executable is for win32 and ia32
### Test method
1. Zipped the folder in .dist
2. Copied to another windowd pc
3. Ran the .exe

Both the generation and testing was performed on a windows 10 x64 pc.

**Comment by arboleya** [comment]
Hi @ericdepotter, Meteor isn't needed.

I'm gonna check this.

In this meanwhile, I've just released a new version some mins ago, with a complete revamp of the project.

Can you please update and let me know if this problems still persists?

Tks

**Comment by ericdepotter** [comment]
Hi,

I just tested to run my app with the new version of Electrify, but now I get this message:
`electrify:meteor:index@server: cannot initialize connection. Did you `npm install -g electrify`?`

I did not install electrify with npm and this worked fine in the previous version. Is this required now and if so how do you install with npm on Windows?

**Comment by arboleya** [comment]
Yes, `electrify` npm package is mandatory now.

You can install it like this:

```
npm install -g electrify
```

**Comment by ericdepotter** [comment]
Ok, I installed electrify and packaged the app succesful, however when running the app on another computer wihout Meteor installed, the same error came up.

**Comment by arboleya** [comment]
Can't see how this can be happening.

You're packaging the app like `electrify package`?

And then opening it by double-clicking the `.exe` file inside the `.dist` folder?

**Comment by rogerkirkness** [comment]
I am getting the same error here, same conditions. First it was because I tried to deploy only the .exe (can see the shortcomings of this now) to 3rd party user Windows machine. Now it is throwing the same JS error when it is run from the .dist output. It runs perfectly fine on Win10 64x dev machine and breaks on Win8 64x user machine despite being the exact same folder. Same js error pops up on run.

**Comment by arboleya** [comment]
Thanks for the feedbacks, I'll give it a deeper look.

**Comment by ericdepotter** [comment]
Here are the detailed steps, I did to test this:
1. Installed electrify using npm.
2. Ran `electrify` in the app's base folder.
3. Changed the name of the app in `package.json` in the folder `./.electrify`.
4. Packaged the app by running `electrify package`.
5. Tested the app by running the .exe in `./.electrify/.dist/$name-of-app$-win32-x64`.
6. Zipped the map in the .dist folder.
7. Moved the zip to another computer.
8. Extracted and ran the .exe in the extracted folder.

**Comment by arboleya** [comment]
Should be fixed in `2.0.1`, please update and let me know if worked as expected.

Tks for reporting.

**Comment by rogerkirkness** [comment]
Thank you Arboleya. Now when I run 'electrify package' it returns the below:

![console](https://cloud.githubusercontent.com/assets/6105317/11041297/fe63b096-86de-11e5-99d2-6f49ad5ecd2d.png)

**Comment by arboleya** [comment]
Oh snap, I'll check it.

**Comment by ericdepotter** [comment]
I have the same error when I run `electrify` in the app's map.

**Comment by arboleya** [comment]
Now I believe it's fixed, in version `2.0.2`.

Can you guys please update and try again?

**Comment by rogerkirkness** [comment]
Thank you. This time it got further, ran for ~4 minutes working on it, and threw this: 
![console2](https://cloud.githubusercontent.com/assets/6105317/11048022/78140f2a-8703-11e5-8b02-1a756ac348cc.png)

**Comment by arboleya** [comment]
@rogerkirkness This has nothing to do with the previous error, actually seems like a permission problem in window's filesystem. Error rises when Electrify attempts to move the bundled meteor app dir inside the `.dist` folder.

I myself had **lots** of problems with Windows filesystem, for many times I've have to completely delete my app, clone it again and restart. It worked many times, but in worse cases I've to restart the machine.

Can you test some things around it? Have in mind it's a filesystem permission problem. In my case, windows always thought my dir was in use so it can't move forward.

Please let me know how it went.

**Comment by rogerkirkness** [comment]
Sure. I guess the only difference was it didn't do this before, but as you
say it could be some kind of lingering file system issue. I will try
cloning/deleting and moving it into root and stuff and get back to you.

**Comment by rogerkirkness** [comment]
Got it working on dev machine after reboot. Will confirm when it is working on client.

**Comment by rogerkirkness** [comment]
It is working! Thank you for your work on this, and such quick turn around. I tried it on one machine so far but will be trying it on two more soon.

**Comment by arboleya** [comment]
Glad to hear it, closing the :)

**Comment by ericdepotter** [comment]
It also works for me, thanks @arboleya for your fast fixes.

**Comment by challett** [comment]
I am still getting this original issue on `2.0.2`

**Comment by rogerkirkness** [comment]
Did you delete the .electrify folder and then re-package it? If so, then I
am not sure what to suggest. It is working on several different client
devices for me right now.

**Comment by challett** [comment]
@rogerkirkness Removing the folder fixed the issue.  Thank you
