### ISSUE TITLE
[Windows - V 2.0.0 ] bundling meteor -> shell.js internal error

### ISSUE THREAD

**Issue by d62remi** [arboleya/electrify#22]
Hi,

When I running app with : 

```
cd leaderboard
electrify
```

works great =D

Now here is the error I by running : 

```
electrify package
```

![image](https://cloud.githubusercontent.com/assets/11924796/10941266/e9fcf73e-830a-11e5-9607-5cfc72aa8813.png)

I had the same error `1.4.0` version in meteor shell

My username is : 
![image](https://cloud.githubusercontent.com/assets/11924796/10941465/d35ff1ba-830b-11e5-86fb-51b79d4772ed.png)

The same path
`C:\Users\RBOUDE~1.AEI\AppData\Local\Temp\Electrify\bundling\bundle` exist
`C:\Users\r.boude***.AEI_02\AppData\Local\Temp\electrify\bundling\bundle` exist 

An explanation ?

It's a great job ! Thanks ;-)

**Comment by d62remi** [comment]
I resolved my problem by creating a project on disk `C:`

^^

**Comment by arboleya** [comment]
Oh fine, it was something with file permissions.

Glad you've fixed. :)

**Comment by akolnati** [comment]
Had the same problem...moved my entire project to C drive and it worked
