### ISSUE TITLE
Meteor is not defined

### ISSUE THREAD

**Issue by sangyoo91** [arboleya/electrify#27]
I tried both
`
$ meteor run
`
`
$ electrify
`

But both are not working and in the browser console,
`
Meteor is not defined
`
This is what I get..

```
head
  title Marker
  meta(charset="UTF-8")
  meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui")
body
  .editor-container
    .textarea-wrapper
      .textarea-header
        .left
          span MARKDOWN
    .preview-wrapper
      .preview-header
        .left
          span MARKDOWN
```

This is all I have done in my project so far.

**Comment by arboleya** [comment]
@sangyoo91 Hi, did you installed meteor in the first place? It seems you didn't.

Install Meteor and try again, it should work. :)
