### ISSUE TITLE
Moving package dist to another folder breaks launch

### ISSUE THREAD

**Issue by AlexDel** [arboleya/electrify#39]
Hello! Sorry for my meteor incompetence, but I have some issue:

I built my app on Win10, launched the exe file and it worked perfectly. But when I move the packaged directory to another folder in my computer and try to run exe there, the project refuse to launch. 

Could you please comment upon possible causes of this or provide some hints on how to fix it.

Thanks!

**Comment by arboleya** [comment]
Hello @AlexDel, did you manage to get it working?

**Comment by AlexDel** [comment]
Hello @arboleya 
Yes, the issue was that we used some npm dependencies that were not installed automatically. Manual installation fixed the case.
