### ISSUE TITLE
Packaged app won't work outside .dist directory

### ISSUE THREAD

**Issue by fvilers** [arboleya/electrify#4]
Hi, first of all, thanks for this promising package!

I'm giving a try to it and packaged the Meteor's demo "todos" app. The packaged app is working correctly inside the .dist directory but if I move the directory "Electrified-win32-ia32" elsewhere on the file system, it doesn't. The app is starting but nothing appears, the viewport stays blank.

Fabian

**Comment by AlexFrazer** [comment]
+1
Coming across the same problem myself

**Comment by arboleya** [comment]
Problem confirmed, I'm gonna look into it.

**Comment by fvilers** [comment]
Thanks !

**Comment by arboleya** [comment]
Fixed in last release, please update.

``` shell
meteor remove arboleya:electrify && meteor add arboleya:electrify
```

Can you guys please check it and confirm if it is working?

Tks for reporting.

**Comment by arboleya** [comment]
@AlexFrazer If you're using the `npm` way to package the app, remember to update the npm package it as well.

**Comment by fvilers** [comment]
Thanks for the fix, it works like a charm.

**Comment by arboleya** [comment]
:beers:
