### ISSUE TITLE
convert from webapp to desktop 

### ISSUE THREAD

**Issue by stallter4** [arboleya/electrify#62]
Hi... I have a simple, probably green question.  If I create my web app in meteor, mongodb, and node.js, and make it fully functional in the web does electrify just require me to download, add a few dependencies and it spits out an .exe that can be ran on any similar operating system?

**Comment by cosmin-novac** [comment]
It creates an executable that will run on that specific operating system.

**Comment by stallter4** [comment]
Wow. Amazing.  So I can concentrate on the web app for now and when its 100% I can quickly make into a desktop app. That's wild

**Comment by stallter4** [comment]
so its true that I can build my meteor app without a thought give to electrify, then if business demands a desktop version I can electrify the thing in a couple days?
