### ISSUE TITLE
Doesn't seem to work on Windows, Has error indicating its processing a .cmd as javascript

### ISSUE THREAD

**Issue by keithn** [arboleya/electrify#8]
20150910-16:21:22.859(12)? (STDERR)
W20150910-16:21:22.860(12)? (STDERR) C:\Sandpit\leaderboard.electrify\node_modules.bin\electron.cmd:1
W20150910-16:21:22.860(12)? (STDERR) (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
W20150910-16:21:22.860(12)? (STDERR)                                                               ^
W20150910-16:21:22.864(12)? (STDERR) SyntaxError: Unexpected token ILLEGAL
W20150910-16:21:22.864(12)? (STDERR)     at Module._compile (module.js:439:25)
W20150910-16:21:22.864(12)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20150910-16:21:22.864(12)? (STDERR)     at Module.load (module.js:356:32)
W20150910-16:21:22.864(12)? (STDERR)     at Function.Module._load (module.js:312:12)
W20150910-16:21:22.864(12)? (STDERR)     at Function.Module.runMain (module.js:497:10)
W20150910-16:21:22.864(12)? (STDERR)     at startup (node.js:119:16)
W20150910-16:21:22.865(12)? (STDERR)     at node.js:929:3

Also tried to bundle it as a app using the NPM tools,  it says it completed ok, but no program is in the .dist folder.

**Comment by arboleya** [comment]
@keithn Which version of Windows?

**Comment by keithn** [comment]
on windows 10

**Comment by arboleya** [comment]
Oh fine, I've spoted the issue through the source. It's simple, I'm going to release a fix for it this weekend.

**Comment by keithn** [comment]
awesome! :)  this is gonna be so goooooood :)

**Comment by arboleya** [comment]
Fixed in `1.2.2`, please update.

I couldn't test on a Windows 10, so pls let me know if it worked.

Tks for reporting.

**Comment by keithn** [comment]
Yes, now when I run meteor I get the app.  Also if I run meteor shell and electrify the app, I get an app to run in the .dist
Thanks!
